### PR TITLE
Support spaces between JSON key/value

### PR DESCRIPTION
**Pull request by ctf0**
account for having a space between the key & value

### CODE REVIEW

**Comment by ivanvermeyen** [comment]
Hi, thanks for the pull.
I was trying to find out why it failed the tests.
Seems the middle wildcard would allow other locale keys to be between the required locale and the the value we're searching for... thus returning a false positive.
Dunno if there is another way except tacking on another where clause.

**Comment by ctf0** [comment]
i added the wildcard to be back compatible, but honestly i've never seen a json field without space between key & value, unless the user is saving the data with custom format.

otherwise we can remove the wildcard and add an empty space instead.

**Comment by ivanvermeyen** [comment]
Hmm, I just checked one of my projects that use `spatie/laravel-translatable` and there is indeed a space.
Weird that there is no space in the test database.

**Comment by ivanvermeyen** [comment]
Ok, I found the reason... 

With spaces when you use a `json` field (MySQL > 5.7 only):

```php
$table->json('name')->nullable();
```

Without spaces if you use a `text` field:

```php
$table->text('name')->nullable();
```

PHP's `json_encode` function that is used by the `laravel-translatable` package doesn't use spaces.
Those seem to be added by MySQL if you use a `json` field.

**Comment by ctf0** [comment]
using `json` yes

**Comment by ivanvermeyen** [comment]
Until we find a better solution, the `orWhere` clause seems to do the trick...
Thanks for catching this, and for the pull request! 👍

**Pull request merged**
